config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  authenticated :user do
    root 'docs#index', as: 'authenticated_root'
  end

  root 'welcome#index'
  resources :docs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :user
  mount_uploader :archive, ArchiveUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :find_doc, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  def index
    @docs = Doc.where(user_id: current_user).order('created_at DESC')
  end

  def show
  end

  def new
    @doc = current_user.docs.build
  end

  def create
    @doc = current_user.docs.build(doc_params)

    if @doc.save
      redirect_to @doc
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @doc.update(doc_params)
      redirect_to @doc
    else
      render 'edit'
    end
  end

  def destroy
    @doc.destroy
    redirect_to docs_path
  end

  private

    def find_doc
      @doc = Doc.find(params[:id])
    end

    def doc_params
      params.require(:doc).permit(:title, :content, :archive)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.haml
= simple_form_for @doc do |f|
  = f.input :title, class:"form-control"
  = f.input :content, class:"form-control"
  = f.label :archive
  = f.file_field :archive
  %br
  = f.button :submit

app/views/docs/edit.html.haml
%section#feature.section-padding
  .container
    .row
      .col-md-6
        .section-title
          %h2.head-title Edit Doc
          %hr.botm-line
            = render 'form'

            = link_to "Cancel", docs_path

app/views/docs/index.html.haml
%section#feature.section-padding
  .container
    .row
      .col-md-6
        .section-title
          %h2.head-title
          -if @docs.size < 1
            %p There are no documents yet!
            %p Start adding one :)
            = link_to "Create Doc", new_doc_path, class:"btn btn-success"
          -else
            %h2.head-title Docs
            %hr.botm-line
            - @docs.each do |doc|
              %h2= link_to doc.title, doc
              %p= time_ago_in_words doc.created_at
              %p= truncate(doc.content, lenght:50)
            %hr

app/views/docs/new.html.haml
%section#feature.section-padding
  .container
    .row
      .col-md-6
        .section-title
          %h2.head-title New Doc
          %hr.botm-line
            = render 'form'

app/views/docs/show.html.haml
%section#feature.section-padding
  .container
    .row
      .col-md-6
        .section-title
          %h2.head-titl= @doc.title
          %hr.botm-line
          %p= @doc.content
          = link_to "Download", @doc.archive.url, class:"btn btn-default"
          %br
          %br
          = link_to "All Docs", docs_path, class:"btn btn-primary"
          = link_to "Edit Doc", edit_doc_path(@doc), class:"btn btn-warning"
          = link_to "Delete", doc_path(@doc), method: :delete, data: { confirm: "Are you sure?"}, class:"btn btn-danger"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title File Cabinet
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %title File Cabinet
    %link{:href => "https://fonts.googleapis.com/css?family=Lato:400,700,300|Open+Sans:400,600,700,300", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "/css/bootstrap.min.css", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "/css/font-awesome.min.css", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "/css/animate.css", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "/css/style.css", :rel => "stylesheet", :type => "text/css"}/


  %body
    = render 'partials/menu'
    = yield
    = render 'partials/footer'
    %script{src:"/js/jquery.min.js"}
    %script{src:"/js/bootstrap.min.js"}

    - if current_page?("/") && !user_signed_in?
      %script{src:"/js/jquery.easing.min.js"}
      %script{src:"/js/wow.js"}
      %script{src:"/js/custom.js"}

app/views/partials/_footer.html.erb
<footer class="navbar-fixed-bottom" id="footer">
    <div class="container">
        <div class="row">
            <div class="col-sm-7 footer-copyright">
                © File Cabinet - All rights reserved
            </div>
            <div class="col-sm-5 footer-social">
                <div class="pull-right hidden-xs hidden-sm">
                    <a href="#"><i class="fa fa-facebook"></i></a>
                    <a href="#"><i class="fa fa-dribbble"></i></a>
                    <a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-google-plus"></i></a>
                    <a href="#"><i class="fa fa-pinterest"></i></a>
                </div>
            </div>
        </div>
    </div>
</footer>

app/views/partials/_menu.html.erb
<% if !user_signed_in? && current_page?("/") %>
  <nav class="nav navbar-default navbar-fixed-top">
<% else %>
  <nav class="nav navbar-default navbar-fixed-top top-nav-collapse">
<% end %>
    <div class="container">
        <div class="col-md-12">
            <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#mynavbar" aria-expanded="false" aria-controls="navbar">
                <span class="fa fa-bars"></span>
            </button>
                <%= link_to "File Cabinet", root_path, class:"navbar-brand" %>
            </div>
            <div class="collapse navbar-collapse navbar-right" id="mynavbar">
                <ul class="nav navbar-nav">
                    <% unless user_signed_in? %>
                      <li class="active"><a href="/#header" class="menu">Home</a></li>
                      <li><a href="/#feature" class="menu">Feature</a></li>
                      <li><%= link_to "Log In", new_user_session_path %></li>
                    <% else %>

                    <li><%= link_to "Create Doc", new_doc_path %></li>
                    <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete%></li>
                    <% end %>
                </ul>
            </div>
        </div>
    </div>
</nav>

app/views/welcome/index.html.erb
    <header class="main-header" id="header">
        <div class="bg-color">
            <div class="container text-center">
                <div class="wrapper wow fadeInUp delay-05s" >
                    <h2 class="top-title">Storage & Sharing</h2>
                    <h3 class="title">File Cabinet</h3>
                    <h4 class="sub-title">Save your entire Life</h4>
                    <button type="submit" class="btn btn-submit" onclick="location.href='/users/sign_up';">Join Now</button>
                </div>
            </div>
        </div>
    </header>
    <!--/ header-->
    <!---->
    <section id="feature" class="section-padding">
        <div class="container">
            <div class="row">
                <div class="col-md-3 wow fadeInLeft delay-05s">
                    <div class="section-title">
                        <h2 class="head-title">Features</h2>
                        <hr class="botm-line">
                        <p class="sec-para">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..</p>
                    </div>
                </div>
                <div class="col-md-9">
                    <div class="col-md-6 wow fadeInRight delay-02s">
                        <div class="icon">
                            <i class="fa fa-paint-brush"></i>
                        </div>
                        <div class="icon-text">
                            <h3 class="txt-tl">Easy to Learn and Design</h3>
                            <p class="txt-para">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id ligula felis euismod semper. </p>
                        </div>
                    </div>
                    <div class="col-md-6 wow fadeInRight delay-02s">
                        <div class="icon">
                            <i class="fa fa-cogs"></i>
                        </div>
                        <div class="icon-text">
                            <h3 class="txt-tl">Bootstrap 3.3.2</h3>
                            <p class="txt-para">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id ligula felis euismod semper. </p>
                        </div>
                    </div>
                    <div class="col-md-6 wow fadeInRight delay-04s">
                        <div class="icon">
                            <i class="fa fa-mobile"></i>
                        </div>
                        <div class="icon-text">
                            <h3 class="txt-tl">Responsive Design</h3>
                            <p class="txt-para">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id ligula felis euismod semper. </p>
                        </div>
                    </div>
                    <div class="col-md-6 wow fadeInRight delay-04s">
                        <div class="icon">
                            <i class="fa fa-desktop"></i>
                        </div>
                        <div class="icon-text">
                            <h3 class="txt-tl">No Coding, No Shortcodes</h3>
                            <p class="txt-para">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id ligula felis euismod semper. </p>
                        </div>
                    </div>
                    <div class="col-md-6 wow fadeInRight delay-06s">
                        <div class="icon">
                            <i class="fa fa-lightbulb-o"></i>
                        </div>
                        <div class="icon-text">
                            <h3 class="txt-tl">High Coversion</h3>
                            <p class="txt-para">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id ligula felis euismod semper. </p>
                        </div>
                    </div>
                    <div class="col-md-6 wow fadeInRight delay-06s">
                        <div class="icon">
                            <i class="fa fa-clock-o"></i>
                        </div>
                        <div class="icon-text">
                            <h3 class="txt-tl">Save Tons of Time</h3>
                            <p class="txt-para">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id ligula felis euismod semper. </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!---->
    <!---->